import Image from 'next/image';
// data.js
export const cardData = [
    {
        id: 1,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 1",
        type: "Vent",
        location: "52 rue badr les amicale",
        category: "Apartment",
        bedrooms: 1,
        kitchen:1,
        bathrooms: 1,
        area: "120 m²",
        floor: "Floor 1",
        price: "$200,000",
        phone: "+1234567890",
        whatsapp: "1234567890", // Added comma here
        images: [ // Corrected: Added comma after whatsapp property
        {alt: 'image1', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2FCenter-pictures%2FIMG_4075.jpg?alt=media&token=0fbbc107-22b2-4fed-bbfb-f680799d7075'},
        {alt: 'image2', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2FCenter-pictures%2FIMG_4076.jpg?alt=media&token=4c3ee7dd-e27e-468d-8917-980f9423b292'},
        { alt: 'image3', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F3.jpg?alt=media&token=1ee28e5c-4382-43a8-8486-70a300389152' },
            { alt: 'image4', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F4.jpg?alt=media&token=c743a9a4-fd9f-402a-aac8-2a43344d72c8' },
            { alt: 'image5', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F5.jpg?alt=media&token=3db9b4fe-05de-49e4-a3ba-0c56756ab4b9' },
            { alt: 'image6', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F6.jpg?alt=media&token=cd3f5727-dd69-495d-be36-a476990c0a1e' },
            { alt: 'image7', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F7.jpg?alt=media&token=0832fc09-a5ec-4a4c-9a71-e6463c6d9244' },
            { alt: 'image8', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F8.jpg?alt=media&token=8addc46f-e121-4456-a129-5e44f4bff1c9' },
            { alt: 'image9', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F9.jpg?alt=media&token=530b17a3-fc1e-4e22-99ec-d8cfa51f71b4' },
            { alt: 'image10', url: 'https://firebasestorage.googleapis.com/v0/b/oceangallery-d06ae.appspot.com/o/Gallery%2Fevenement%20-%20infermiere%202024-06-02%2F10.jpg?alt=media&token=f840572c-7b17-42da-a413-565daf589f3e' }
        ]
    },
    {
        id: 2,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 2,
        bathrooms: 2,
        kitchen:1,
        area: "50 m²",
        floor: "Floor 1",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 3,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 1",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 3,
        bathrooms: 3,
        kitchen:1,
        area: "60 m²",
        floor: "Floor 2",
        price: "$200,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 4,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 4,
        bathrooms: 4,
        kitchen:1,
        area: "80 m²",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 5,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Condo",
        bedrooms: 5,
        bathrooms: 5,
        kitchen:1,
        area: "180 m²",
        floor: "Floor 2",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 6,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 6,
        bathrooms: 6,
        kitchen:1,
        area: "780 m²",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 7,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 7,
        bathrooms: 7,
        kitchen:1,
        area: "90 m²",
        floor: "Floor 3",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 8,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Commercial property",
        bedrooms: 8,
        bathrooms: 8,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 3",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 9,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 9,
        bathrooms: 9,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 4",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 10,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Commercial property",
        bedrooms: 10,
        bathrooms: 10,
        kitchen:1,
        area: "110 m²",
        floor: "Floor 4",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },{
        id: 11,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 11,
        bathrooms: 11,
        kitchen:1,
        area: "180 m²",
        floor: "Floor 5",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 12,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 12,
        bathrooms: 12,
        kitchen:1,
        area: "120 m²",
        floor: "Floor 5",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },{
        id: 13,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Condo",
        bedrooms: 13,
        bathrooms: 13,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 6",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 14,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 14,
        bathrooms: 14,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 6",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 15,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 1",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 1,
        bathrooms: 1,
        kitchen:1,
        area: "120 m²",
        floor: "Floor 7",
        price: "$200,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 16,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 2,
        bathrooms: 2,
        kitchen:1,
        area: "50 m²",
        floor: "Floor 7",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 17,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 1",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 3,
        bathrooms: 3,
        kitchen:1,
        area: "60 m²",
        floor: "Floor 8",
        price: "$200,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 18,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 4,
        bathrooms: 4,
        kitchen:1,
        area: "80 m²",
        floor: "Floor 8",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 19,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Condo",
        bedrooms: 5,
        bathrooms: 5,
        kitchen:1,
        area: "180 m²",
        floor: "Floor 9",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 20,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 6,
        bathrooms: 6,
        kitchen:1,
        area: "780 m²",
        floor: "Floor 9",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 21,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 7,
        bathrooms: 7,
        kitchen:1,
        area: "90 m²",
        floor: "Floor 10",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 22,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Commercial property",
        bedrooms: 8,
        bathrooms: 8,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 10",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 23,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 9,
        bathrooms: 9,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 11",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 24,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Commercial property",
        bedrooms: 10,
        bathrooms: 10,
        kitchen:1,
        area: "110 m²",
        floor: "Floor 11",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },{
        id: 25,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Apartment",
        bedrooms: 11,
        bathrooms: 11,
        kitchen:1,
        area: "180 m²",
        floor: "Floor 12",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 26,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"Villa",
        bedrooms: 12,
        bathrooms: 12,
        kitchen:1,
        area: "120 m²",
        floor: "Floor 12",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },{
        id: 27,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Vent",
        location:"52 rue badr les amicale",
        category:"Condo",
        bedrooms: 13,
        bathrooms: 13,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 13",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    {
        id: 28,
        imageSrc: "/images/card.jpeg",
        title: "Beautiful House 2",
        type: "Location",
        location:"52 rue badr les amicale",
        category:"House",
        bedrooms: 14,
        bathrooms: 14,
        kitchen:1,
        area: "150 m²",
        floor: "Floor 13",
        price: "$300,000",
        phone: "+1234567890",
        whatsapp: "1234567890"
    },
    // Add more card objects as needed
];
export const steps = [
    {
        image: "/images/1.svg",
        title: "Préparez Vos Finances",
        description: "Examinez votre budget et votre situation financière pour vous assurer d'être prêt pour une transaction immobilière. Évitez les changements financiers majeurs pendant six mois.",
        linkText: "Essayez ce calculateur",
        linkUrl: "#",
    },
    {
        image: "/images/2.svg",
        title: "Obtenez une Pré-Qualification",
        description: "Évaluez rapidement votre capacité financière pour rechercher des maisons dans votre budget sans impacter votre crédit.",
        linkText: "Préqualifiez-vous aujourd'hui",
        linkUrl: "#",
    },
    {
        image: "/images/3.svg",
        title: "Préparez-vous à Faire une Offre",
        description: "Rassemblez les documents nécessaires et identifiez les propriétés qui vous intéressent. Notre équipe est là pour vous aider à naviguer sur le marché.",
        linkText: "Explorez les annonces",
        linkUrl: "#",
    },
    {
        image: "/images/4.svg",
        title: "Faites une Offre",
        description: "Une fois que vous trouvez une propriété qui vous plaît, nous vous aiderons à faire une offre compétitive. Nos agents vous guideront tout au long du processus.",
        linkText: "Contactez-nous",
        linkUrl: "#",
    },
    {
        image: "/images/5.svg",
        title: "Finalisez l'Affaire et Emménagez",
        description: "Félicitations ! Une fois votre offre acceptée, nous vous guiderons à travers le processus de clôture pour finaliser votre achat ou votre location.",
        linkText: "Commencez ici",
        linkUrl: "#",
    },

];
